<!DOCTYPE html>
<!-- This file has been generated by tj3 v3.7.1 -->
<html lang="en" xml:lang="en">
 <head>
  <title>Reductive Catalytic Lignin-first Fractionation - Plan</title>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="IE=9" http-equiv="X-UA-Compatible"/>
  <meta content="TaskJuggler Report" name="description"/>
  <meta content="taskjuggler, project, management" name="keywords"/>
 </head>
 <link href="css/tjreport.css" rel="stylesheet" type="text/css"></link>
 <!-- Dynamic Report ID: 0 -->
 <body>
  <script src="scripts/wz_tooltip.js" type="text/javascript"></script>
  <noscript><div style="text-align:center; color:#FF0000">This page requires Javascript for full functionality. Please enable it
in your browser settings!
</div></noscript>
  <div class="tj_page">
   <div><h1 id="Lignin_Extraction_with_Continuous_Reductive_Catalytic_Fractionation">Lignin Extraction with Continuous Reductive Catalytic Fractionation</h1></div>
   <table cellspacing="0" class="tj_text_page"><tr class="tj_text_row"><td class="tj_column_center" style="width:100%; "><div>
       <!-- Dynamic Report ID: 0.0 -->
       <table cellspacing="1" class="tj_table_frame">
        <tr><td><div class="tj_table_headline"><div>Project Gantt Chart</div></div></td></tr>
        <tr><td><table cellspacing="1" class="tj_table"><tbody>
            <tr class="tabhead" style="height:39px; font-size:15px;">
             <td class="tabcell"><table cellspacing="0" class="tj_table_header_cell" style="text-align:center; "><tr><td class="tj_table_cell_label" style="overflow:hidden; white-space:normal; font-weight:bold; min-width: 692px; max-width: 692px; ">Name</td></tr></table></td>
             <td rowspan="28" style="padding:0px; vertical-align:top;"><div class="tabback" style="position:relative; overflow:auto; width:392px; height:611px;"><div style="margin:0px; padding:0px; position:absolute; overflow:hidden; top:0px; left:0px; width:392px; height:611px; font-size:10px;">
                <div class="tabback" style="margin:0px; padding:0px; position:relative; width:392px; height:39px; font-size:9px; ">
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:-104px; top:0px; width:112px; height:19px; "><div style="padding:3px; ">2023</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:9px; top:0px; width:113px; height:19px; "><div style="padding:3px; ">2024</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:123px; top:0px; width:112px; height:19px; "><div style="padding:3px; ">2025</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:236px; top:0px; width:113px; height:19px; "><div style="padding:3px; ">2026</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:350px; top:0px; width:112px; height:19px; "><div style="padding:3px; ">2027</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:-85px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q1</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:-57px; top:20px; width:28px; height:19px; "><div style="padding:3px; ">Q2</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:-28px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q3</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:0px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q4</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:28px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q1</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:56px; top:20px; width:28px; height:19px; "><div style="padding:3px; ">Q2</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:85px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q3</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:113px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q4</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:141px; top:20px; width:28px; height:19px; "><div style="padding:3px; ">Q1</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:170px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q2</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:198px; top:20px; width:28px; height:19px; "><div style="padding:3px; ">Q3</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:227px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q4</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:255px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q1</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:283px; top:20px; width:28px; height:19px; "><div style="padding:3px; ">Q2</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:312px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q3</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:340px; top:20px; width:27px; height:19px; "><div style="padding:3px; ">Q4</div></div>
                 <div class="tabhead" style="font-weight:bold; position:absolute; left:368px; top:20px; width:28px; height:19px; "><div style="padding:3px; ">Q1</div></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:40px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:23px; top:0px; width:360px; height:21px;"></div>
                 <div class="containerbar" style="left:23px; top:5px; width:360px; height:5px;"></div>
                 <div class="tj_gantt_jag" style="left:23px; top:10px;"></div>
                 <div class="tj_gantt_jag" style="left:373px; top:10px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:62px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:28px; top:0px; width:10px; height:21px;"></div>
                 <div class="taskbarframe" style="left:28px; top:4px; width:10px; height:12px;"></div>
                 <div class="taskbar" style="left:29px; top:5px; width:8px; height:10px;"></div>
                 <div class="progressbar" style="left:29px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:84px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:32px; top:0px; width:350px; height:21px;"></div>
                 <div class="containerbar" style="left:32px; top:5px; width:350px; height:5px;"></div>
                 <div class="tj_gantt_jag" style="left:32px; top:10px;"></div>
                 <div class="tj_gantt_jag" style="left:372px; top:10px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:106px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:37px; top:0px; width:105px; height:21px;"></div>
                 <div class="taskbarframe" style="left:37px; top:4px; width:105px; height:12px;"></div>
                 <div class="taskbar" style="left:38px; top:5px; width:103px; height:10px;"></div>
                 <div class="progressbar" style="left:38px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:128px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:151px; top:0px; width:114px; height:21px;"></div>
                 <div class="taskbarframe" style="left:151px; top:4px; width:114px; height:12px;"></div>
                 <div class="taskbar" style="left:152px; top:5px; width:112px; height:10px;"></div>
                 <div class="progressbar" style="left:152px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:150px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:264px; top:0px; width:113px; height:21px;"></div>
                 <div class="taskbarframe" style="left:264px; top:4px; width:113px; height:12px;"></div>
                 <div class="taskbar" style="left:265px; top:5px; width:111px; height:10px;"></div>
                 <div class="progressbar" style="left:265px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:172px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:32px; top:0px; width:87px; height:21px;"></div>
                 <div class="containerbar" style="left:32px; top:5px; width:87px; height:5px;"></div>
                 <div class="tj_gantt_jag" style="left:32px; top:10px;"></div>
                 <div class="tj_gantt_jag" style="left:109px; top:10px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:194px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:37px; top:0px; width:39px; height:21px;"></div>
                 <div class="taskbarframe" style="left:37px; top:4px; width:39px; height:12px;"></div>
                 <div class="taskbar" style="left:38px; top:5px; width:37px; height:10px;"></div>
                 <div class="progressbar" style="left:38px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:216px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:75px; top:0px; width:39px; height:21px;"></div>
                 <div class="taskbarframe" style="left:75px; top:4px; width:39px; height:12px;"></div>
                 <div class="taskbar" style="left:76px; top:5px; width:37px; height:10px;"></div>
                 <div class="progressbar" style="left:76px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:238px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:32px; top:0px; width:106px; height:21px;"></div>
                 <div class="containerbar" style="left:32px; top:5px; width:106px; height:5px;"></div>
                 <div class="tj_gantt_jag" style="left:32px; top:10px;"></div>
                 <div class="tj_gantt_jag" style="left:128px; top:10px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:260px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:37px; top:0px; width:86px; height:21px;"></div>
                 <div class="taskbarframe" style="left:37px; top:4px; width:86px; height:12px;"></div>
                 <div class="taskbar" style="left:38px; top:5px; width:84px; height:10px;"></div>
                 <div class="progressbar" style="left:38px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:282px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:75px; top:0px; width:58px; height:21px;"></div>
                 <div class="taskbarframe" style="left:75px; top:4px; width:58px; height:12px;"></div>
                 <div class="taskbar" style="left:76px; top:5px; width:56px; height:10px;"></div>
                 <div class="progressbar" style="left:76px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:304px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:32px; top:0px; width:181px; height:21px;"></div>
                 <div class="containerbar" style="left:32px; top:5px; width:181px; height:5px;"></div>
                 <div class="tj_gantt_jag" style="left:32px; top:10px;"></div>
                 <div class="tj_gantt_jag" style="left:203px; top:10px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:326px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:37px; top:0px; width:113px; height:21px;"></div>
                 <div class="taskbarframe" style="left:37px; top:4px; width:113px; height:12px;"></div>
                 <div class="taskbar" style="left:38px; top:5px; width:111px; height:10px;"></div>
                 <div class="progressbar" style="left:38px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:348px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:151px; top:0px; width:57px; height:21px;"></div>
                 <div class="taskbarframe" style="left:151px; top:4px; width:57px; height:12px;"></div>
                 <div class="taskbar" style="left:152px; top:5px; width:55px; height:10px;"></div>
                 <div class="progressbar" style="left:152px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:370px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:32px; top:0px; width:340px; height:21px;"></div>
                 <div class="containerbar" style="left:32px; top:5px; width:340px; height:5px;"></div>
                 <div class="tj_gantt_jag" style="left:32px; top:10px;"></div>
                 <div class="tj_gantt_jag" style="left:362px; top:10px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:392px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:37px; top:0px; width:113px; height:21px;"></div>
                 <div class="taskbarframe" style="left:37px; top:4px; width:113px; height:12px;"></div>
                 <div class="taskbar" style="left:38px; top:5px; width:111px; height:10px;"></div>
                 <div class="progressbar" style="left:38px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:414px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:37px; top:0px; width:85px; height:21px;"></div>
                 <div class="taskbarframe" style="left:37px; top:4px; width:85px; height:12px;"></div>
                 <div class="taskbar" style="left:38px; top:5px; width:83px; height:10px;"></div>
                 <div class="progressbar" style="left:38px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:436px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:151px; top:0px; width:29px; height:21px;"></div>
                 <div class="taskbarframe" style="left:151px; top:4px; width:29px; height:12px;"></div>
                 <div class="taskbar" style="left:152px; top:5px; width:27px; height:10px;"></div>
                 <div class="progressbar" style="left:152px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:458px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:179px; top:0px; width:188px; height:21px;"></div>
                 <div class="taskbarframe" style="left:179px; top:4px; width:188px; height:12px;"></div>
                 <div class="taskbar" style="left:180px; top:5px; width:186px; height:10px;"></div>
                 <div class="progressbar" style="left:180px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:480px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:174px; top:0px; width:209px; height:21px;"></div>
                 <div class="containerbar" style="left:174px; top:5px; width:209px; height:5px;"></div>
                 <div class="tj_gantt_jag" style="left:174px; top:10px;"></div>
                 <div class="tj_gantt_jag" style="left:373px; top:10px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:502px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:179px; top:0px; width:57px; height:21px;"></div>
                 <div class="taskbarframe" style="left:179px; top:4px; width:57px; height:12px;"></div>
                 <div class="taskbar" style="left:180px; top:5px; width:55px; height:10px;"></div>
                 <div class="progressbar" style="left:180px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:524px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:179px; top:0px; width:57px; height:21px;"></div>
                 <div class="taskbarframe" style="left:179px; top:4px; width:57px; height:12px;"></div>
                 <div class="taskbar" style="left:180px; top:5px; width:55px; height:10px;"></div>
                 <div class="progressbar" style="left:180px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:546px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:236px; top:0px; width:29px; height:21px;"></div>
                 <div class="taskbarframe" style="left:236px; top:4px; width:29px; height:12px;"></div>
                 <div class="taskbar" style="left:237px; top:5px; width:27px; height:10px;"></div>
                 <div class="progressbar" style="left:237px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell1" style="margin:0px; padding:0px; position:absolute; left:0px; top:568px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:264px; top:0px; width:57px; height:21px;"></div>
                 <div class="taskbarframe" style="left:264px; top:4px; width:57px; height:12px;"></div>
                 <div class="taskbar" style="left:265px; top:5px; width:55px; height:10px;"></div>
                 <div class="progressbar" style="left:265px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="taskcell2" style="margin:0px; padding:0px; position:absolute; left:0px; top:590px; width:392px; height:21px; font-size:10px;">
                 <div class="tabvline" style="left:8px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:122px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:235px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:349px; top:0px; width:1px; height:21px;"></div>
                 <div class="tabvline" style="left:462px; top:0px; width:1px; height:21px;"></div>
                 <div class="tj_gantt_frame" style="left:321px; top:0px; width:57px; height:21px;"></div>
                 <div class="taskbarframe" style="left:321px; top:4px; width:57px; height:12px;"></div>
                 <div class="taskbar" style="left:322px; top:5px; width:55px; height:10px;"></div>
                 <div class="progressbar" style="left:322px; top:7px; width:0px; height:6px;"></div>
                 <div class="nowline" style="left:-61px; top:0px; width:1px; height:21px;"></div>
                </div>
                <div class="depline" style="left:38px; top:72px; width:6px; height:1px;"></div>
                <div class="depline" style="left:43px; top:72px; width:1px; height:9px;"></div>
                <div class="depline" style="left:22px; top:80px; width:22px; height:1px;"></div>
                <div class="depline" style="left:22px; top:80px; width:1px; height:15px;"></div>
                <div class="depline" style="left:22px; top:94px; width:11px; height:1px;"></div>
                <div class="depline" style="left:38px; top:72px; width:9px; height:1px;"></div>
                <div class="depline" style="left:46px; top:72px; width:1px; height:12px;"></div>
                <div class="depline" style="left:19px; top:83px; width:28px; height:1px;"></div>
                <div class="depline" style="left:19px; top:83px; width:1px; height:188px;"></div>
                <div class="depline" style="left:19px; top:270px; width:18px; height:1px;"></div>
                <div class="depline" style="left:38px; top:72px; width:12px; height:1px;"></div>
                <div class="depline" style="left:49px; top:72px; width:1px; height:15px;"></div>
                <div class="depline" style="left:16px; top:86px; width:34px; height:1px;"></div>
                <div class="depline" style="left:16px; top:86px; width:1px; height:119px;"></div>
                <div class="depline" style="left:16px; top:204px; width:21px; height:1px;"></div>
                <div class="depline" style="left:38px; top:72px; width:15px; height:1px;"></div>
                <div class="depline" style="left:52px; top:72px; width:1px; height:155px;"></div>
                <div class="depline" style="left:52px; top:226px; width:23px; height:1px;"></div>
                <div class="depline" style="left:142px; top:116px; width:6px; height:1px;"></div>
                <div class="depline" style="left:147px; top:116px; width:1px; height:9px;"></div>
                <div class="depline" style="left:138px; top:124px; width:10px; height:1px;"></div>
                <div class="depline" style="left:138px; top:124px; width:1px; height:15px;"></div>
                <div class="depline" style="left:138px; top:138px; width:13px; height:1px;"></div>
                <div class="depline" style="left:142px; top:116px; width:13px; height:1px;"></div>
                <div class="depline" style="left:154px; top:116px; width:1px; height:419px;"></div>
                <div class="depline" style="left:154px; top:534px; width:25px; height:1px;"></div>
                <div class="depline" style="left:142px; top:116px; width:16px; height:1px;"></div>
                <div class="depline" style="left:157px; top:116px; width:1px; height:397px;"></div>
                <div class="depline" style="left:157px; top:512px; width:22px; height:1px;"></div>
                <div class="depline" style="left:142px; top:116px; width:19px; height:1px;"></div>
                <div class="depline" style="left:160px; top:116px; width:1px; height:441px;"></div>
                <div class="depline" style="left:160px; top:556px; width:76px; height:1px;"></div>
                <div class="depline" style="left:265px; top:138px; width:6px; height:1px;"></div>
                <div class="depline" style="left:270px; top:138px; width:1px; height:9px;"></div>
                <div class="depline" style="left:253px; top:146px; width:18px; height:1px;"></div>
                <div class="depline" style="left:253px; top:146px; width:1px; height:15px;"></div>
                <div class="depline" style="left:253px; top:160px; width:11px; height:1px;"></div>
                <div class="depline" style="left:265px; top:138px; width:9px; height:1px;"></div>
                <div class="depline" style="left:273px; top:138px; width:1px; height:12px;"></div>
                <div class="depline" style="left:250px; top:149px; width:24px; height:1px;"></div>
                <div class="depline" style="left:250px; top:149px; width:1px; height:430px;"></div>
                <div class="depline" style="left:250px; top:578px; width:14px; height:1px;"></div>
                <div class="depline" style="left:76px; top:204px; width:6px; height:1px;"></div>
                <div class="depline" style="left:81px; top:204px; width:1px; height:9px;"></div>
                <div class="depline" style="left:64px; top:212px; width:18px; height:1px;"></div>
                <div class="depline" style="left:64px; top:212px; width:1px; height:81px;"></div>
                <div class="depline" style="left:64px; top:292px; width:11px; height:1px;"></div>
                <div class="depline" style="left:123px; top:270px; width:6px; height:1px;"></div>
                <div class="depline" style="left:128px; top:270px; width:1px; height:89px;"></div>
                <div class="depline" style="left:128px; top:358px; width:23px; height:1px;"></div>
                <div class="depline" style="left:133px; top:292px; width:6px; height:1px;"></div>
                <div class="depline" style="left:138px; top:292px; width:1px; height:9px;"></div>
                <div class="depline" style="left:138px; top:300px; width:3px; height:1px;"></div>
                <div class="depline" style="left:140px; top:300px; width:1px; height:59px;"></div>
                <div class="depline" style="left:140px; top:358px; width:11px; height:1px;"></div>
                <div class="depline" style="left:150px; top:336px; width:14px; height:1px;"></div>
                <div class="depline" style="left:163px; top:336px; width:1px; height:9px;"></div>
                <div class="depline" style="left:137px; top:344px; width:27px; height:1px;"></div>
                <div class="depline" style="left:137px; top:344px; width:1px; height:15px;"></div>
                <div class="depline" style="left:137px; top:358px; width:14px; height:1px;"></div>
                <div class="depline" style="left:150px; top:402px; width:14px; height:1px;"></div>
                <div class="depline" style="left:163px; top:402px; width:1px; height:9px;"></div>
                <div class="depline" style="left:140px; top:410px; width:24px; height:1px;"></div>
                <div class="depline" style="left:140px; top:410px; width:1px; height:37px;"></div>
                <div class="depline" style="left:140px; top:446px; width:11px; height:1px;"></div>
                <div class="depline" style="left:122px; top:424px; width:6px; height:1px;"></div>
                <div class="depline" style="left:127px; top:424px; width:1px; height:23px;"></div>
                <div class="depline" style="left:127px; top:446px; width:24px; height:1px;"></div>
                <div class="depline" style="left:180px; top:446px; width:6px; height:1px;"></div>
                <div class="depline" style="left:185px; top:446px; width:1px; height:9px;"></div>
                <div class="depline" style="left:168px; top:454px; width:18px; height:1px;"></div>
                <div class="depline" style="left:168px; top:454px; width:1px; height:15px;"></div>
                <div class="depline" style="left:168px; top:468px; width:11px; height:1px;"></div>
                <div class="depline" style="left:180px; top:446px; width:9px; height:1px;"></div>
                <div class="depline" style="left:188px; top:446px; width:1px; height:133px;"></div>
                <div class="depline" style="left:188px; top:578px; width:76px; height:1px;"></div>
                <div class="depline" style="left:236px; top:512px; width:6px; height:1px;"></div>
                <div class="depline" style="left:241px; top:512px; width:1px; height:67px;"></div>
                <div class="depline" style="left:241px; top:578px; width:23px; height:1px;"></div>
                <div class="depline" style="left:236px; top:534px; width:9px; height:1px;"></div>
                <div class="depline" style="left:244px; top:534px; width:1px; height:45px;"></div>
                <div class="depline" style="left:244px; top:578px; width:20px; height:1px;"></div>
                <div class="depline" style="left:321px; top:578px; width:6px; height:1px;"></div>
                <div class="depline" style="left:326px; top:578px; width:1px; height:9px;"></div>
                <div class="depline" style="left:310px; top:586px; width:17px; height:1px;"></div>
                <div class="depline" style="left:310px; top:586px; width:1px; height:15px;"></div>
                <div class="depline" style="left:310px; top:600px; width:11px; height:1px;"></div>
                <div class="tj_arrow_head" style="left:27px; top:89px;"></div>
                <div class="tj_arrow_head" style="left:31px; top:265px;"></div>
                <div class="tj_arrow_head" style="left:31px; top:199px;"></div>
                <div class="tj_arrow_head" style="left:69px; top:221px;"></div>
                <div class="tj_arrow_head" style="left:145px; top:133px;"></div>
                <div class="tj_arrow_head" style="left:173px; top:529px;"></div>
                <div class="tj_arrow_head" style="left:173px; top:507px;"></div>
                <div class="tj_arrow_head" style="left:230px; top:551px;"></div>
                <div class="tj_arrow_head" style="left:258px; top:155px;"></div>
                <div class="tj_arrow_head" style="left:258px; top:573px;"></div>
                <div class="tj_arrow_head" style="left:69px; top:287px;"></div>
                <div class="tj_arrow_head" style="left:145px; top:353px;"></div>
                <div class="tj_arrow_head" style="left:145px; top:441px;"></div>
                <div class="tj_arrow_head" style="left:173px; top:463px;"></div>
                <div class="tj_arrow_head" style="left:315px; top:595px;"></div>
               </div></div></td>
            </tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28640', TITLE, 'Reductive Catalytic Lignin-first Fractionation')" style="cursor:help; "><img alt="Icon" src="icons/taskgroup.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; font-weight:bold; min-width: 672px; max-width: 672px; ">Reductive Catalytic Lignin-first Fractionation</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28640" style="cursor:help"><div>
                <b>ID:</b> clff</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:8px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28660', TITLE, 'Initial Verification (psu, ab, fc)')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 664px; max-width: 664px; ">Initial Verification (psu, ab, fc)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28660" style="cursor:help"><div>
                <b>ID:</b> clff.obj1</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:8px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28680', TITLE, 'CLFF process TEA (psu)')" style="cursor:help; "><img alt="Icon" src="icons/taskgroup.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; font-weight:bold; min-width: 664px; max-width: 664px; ">CLFF process TEA (psu)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28680" style="cursor:help"><div>
                <b>ID:</b> clff.obj2</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28700', TITLE, 'Initial TEA')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Initial TEA</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28700" style="cursor:help"><div>
                <b>ID:</b> clff.obj2.task2_1</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28720', TITLE, 'Mid-point TEA (scale evaluation)')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Mid-point TEA (scale evaluation)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28720" style="cursor:help"><div>
                <b>ID:</b> clff.obj2.task2_2</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28740', TITLE, 'Final TEA (refining and scenario analysis)')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Final TEA (refining and scenario analysis)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28740" style="cursor:help"><div>
                <b>ID:</b> clff.obj2.task2_3</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:8px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28760', TITLE, 'Procuring Biomass Feedstocks (fc)')" style="cursor:help; "><img alt="Icon" src="icons/taskgroup.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; font-weight:bold; min-width: 664px; max-width: 664px; ">Procuring Biomass Feedstocks (fc)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28760" style="cursor:help"><div>
                <b>ID:</b> clff.obj3</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28780', TITLE, 'Processing Corn Stover')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Processing Corn Stover</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28780" style="cursor:help"><div>
                <b>ID:</b> clff.obj3.task3_1</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28800', TITLE, 'Processing Reactor Ready Chips')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Processing Reactor Ready Chips</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28800" style="cursor:help"><div>
                <b>ID:</b> clff.obj3.task3_2</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:8px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28820', TITLE, 'Characterizing CLFF Biomass Feedstock (fc, psu)')" style="cursor:help; "><img alt="Icon" src="icons/taskgroup.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; font-weight:bold; min-width: 664px; max-width: 664px; ">Characterizing CLFF Biomass Feedstock (fc, psu)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28820" style="cursor:help"><div>
                <b>ID:</b> clff.obj4</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28840', TITLE, 'Investigating CLFF reactor packing')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Investigating CLFF reactor packing</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28840" style="cursor:help"><div>
                <b>ID:</b> clff.obj4.task4_2</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28860', TITLE, 'Measuring feedstock physical/mechanical properties')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Measuring feedstock physical/mechanical properties</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28860" style="cursor:help"><div>
                <b>ID:</b> clff.obj4.task4_1</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:8px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28880', TITLE, 'Developing a multiphysics CLFF model (psu, ab)')" style="cursor:help; "><img alt="Icon" src="icons/taskgroup.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; font-weight:bold; min-width: 664px; max-width: 664px; ">Developing a multiphysics CLFF model (psu, ab)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28880" style="cursor:help"><div>
                <b>ID:</b> clff.obj5</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28900', TITLE, 'Developing computational multi-physics model')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Developing computational multi-physics model</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28900" style="cursor:help"><div>
                <b>ID:</b> clff.obj5.task5_1</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28920', TITLE, 'Experimental validation of CLFF reactor model')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Experimental validation of CLFF reactor model</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28920" style="cursor:help"><div>
                <b>ID:</b> clff.obj5.task5_2</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:8px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28940', TITLE, 'Developing two-stage CLFF reactor (ab, psu)')" style="cursor:help; "><img alt="Icon" src="icons/taskgroup.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; font-weight:bold; min-width: 664px; max-width: 664px; ">Developing two-stage CLFF reactor (ab, psu)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28940" style="cursor:help"><div>
                <b>ID:</b> clff.obj6</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28960', TITLE, 'Developing CLFF reactor')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Developing CLFF reactor</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28960" style="cursor:help"><div>
                <b>ID:</b> clff.obj6.task6_1</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID28980', TITLE, 'Developing ex-situ reactor')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Developing ex-situ reactor</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID28980" style="cursor:help"><div>
                <b>ID:</b> clff.obj6.task6_2</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29000', TITLE, 'Commissioning of two-stage CLFF reactor system')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Commissioning of two-stage CLFF reactor system</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29000" style="cursor:help"><div>
                <b>ID:</b> clff.obj6.task6_3</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29020', TITLE, 'Improvement of two-stage CLFF reactor system')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Improvement of two-stage CLFF reactor system</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29020" style="cursor:help"><div>
                <b>ID:</b> clff.obj6.task6_4</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:8px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29040', TITLE, 'Lignin-first Fractionation with ex-situ valorization of lignin and holocellulose (psu, ab)')" style="cursor:help; "><img alt="Icon" src="icons/taskgroup.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; font-weight:bold; min-width: 664px; max-width: 664px; ">Lignin-first Fractionation with ex-situ valorization of lignin and holocellulose (psu, ab)</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29040" style="cursor:help"><div>
                <b>ID:</b> clff.obj7</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29060', TITLE, 'Synthesis of catalyst materials')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Synthesis of catalyst materials</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29060" style="cursor:help"><div>
                <b>ID:</b> clff.obj7.task7_1</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29080', TITLE, 'Catalysis screening in a batch reactor')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Catalysis screening in a batch reactor</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29080" style="cursor:help"><div>
                <b>ID:</b> clff.obj7.task7_2</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29100', TITLE, 'Screening continuous reaction conditions')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Screening continuous reaction conditions</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29100" style="cursor:help"><div>
                <b>ID:</b> clff.obj7.task7_3</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell1">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29120', TITLE, 'Lignin Fractionation operation with a CLFF reactor and characterizing lignin fraction')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Lignin Fractionation operation with a CLFF reactor and characterizing lignin fraction</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29120" style="cursor:help"><div>
                <b>ID:</b> clff.obj7.task7_4</div></div>
             </td></tr>
            <tr class="tabline" style="height:21px; font-size:12px; "><td class="taskcell2">
              <table cellspacing="0" class="tj_table_cell" style="text-align:left; height:14px; "><tr>
                <td style="width:16px; "></td>
                <td class="tj_table_cell_icon" onclick="TagToTip('ID29140', TITLE, 'Characterization and analysis of holocellulose fraction')" style="cursor:help; "><img alt="Icon" src="icons/task.png"></img></td>
                <td class="tj_table_cell_label" style="overflow:hidden; white-space:nowrap; min-width: 656px; max-width: 656px; ">Characterization and analysis of holocellulose fraction</td>
               </tr></table>
              <div class="tj_tooltip_box" id="ID29140" style="cursor:help"><div>
                <b>ID:</b> clff.obj7.task7_5</div></div>
             </td></tr>
           </tbody></table></td></tr>
        <tr><td><div class="tj_table_legend_frame"><table cellspacing="1" class="tj_table_legend">
            <tr class="tj_legend_row">
             <td class="tj_legend_spacer"></td>
             <td class="tj_legend_item"><div class="tj_legend_symbol" style="top:3px">
               <div class="tj_gantt_frame" style="left:5px; top:0px; width:36px; height:15px;"></div>
               <div class="containerbar" style="left:5px; top:2px; width:36px; height:5px;"></div>
               <div class="tj_gantt_jag" style="left:5px; top:7px;"></div>
               <div class="tj_gantt_jag" style="left:31px; top:7px;"></div>
              </div></td>
             <td class="tj_legend_item"><div class="tj_legend_label">Container Task</div></td>
             <td class="tj_legend_spacer"></td>
             <td class="tj_legend_item"><div class="tj_legend_symbol" style="top:3px">
               <div class="tj_gantt_frame" style="left:5px; top:0px; width:31px; height:15px;"></div>
               <div class="taskbarframe" style="left:5px; top:1px; width:31px; height:12px;"></div>
               <div class="taskbar" style="left:6px; top:2px; width:29px; height:10px;"></div>
               <div class="progressbar" style="left:6px; top:4px; width:14px; height:6px;"></div>
              </div></td>
             <td class="tj_legend_item"><div class="tj_legend_label">Normal Task</div></td>
             <td class="tj_legend_spacer"></td>
             <td class="tj_legend_item"><div class="tj_legend_symbol" style="top:3px">
               <div class="tj_gantt_frame" style="left:3px; top:0px; width:15px; height:15px;"></div>
               <div class="tj_diamond_top" style="left:4px; top:0px;"></div>
               <div class="tj_diamond_bottom" style="left:4px; top:7px;"></div>
              </div></td>
             <td class="tj_legend_item"><div class="tj_legend_label">Milestone</div></td>
             <td class="tj_legend_spacer"></td>
            </tr>
            <tr class="tj_legend_row">
             <td class="tj_legend_spacer"></td>
             <td class="tj_legend_item"><div class="tj_legend_symbol"><div style="position:relative; top:2px;width:20px; height:15px"><div class="loadstackframe" style="position:absolute; left:5px; width:16px; height:15px;"><div class="offduty" style="position:absolute; left:1px; top:1px; width:14px; height:13px;"></div></div></div></div></td>
             <td class="tj_legend_item"><div class="tj_legend_label">Off-duty period</div></td>
             <td class="tj_legend_item" colspan="3"></td>
             <td class="tj_legend_item" colspan="3"></td>
             <td class="tj_legend_spacer"></td>
            </tr>
           </table></div></td></tr>
       </table>
      </div></td></tr></table>
   <div class="copyright">Project: Reductive Catalytic Lignin-first Fractionation Version: 1.0 - Created on 2023-05-18 16:15:40 with <a href="http://www.taskjuggler.org">TaskJuggler</a> v3.7.1</div>
  </div>
 </body>
</html>
